#!/bin/bash
echo Try...
if ! (cat /proc/net/dev | grep ppp0) > /dev/null 2>&1
  then
    poff -a
    pon dsl-provider
    plog
    ping -c 3 www.google.com
    echo Success
  else
    echo Fail
  fi
date
